### ISSUE TITLE
Hoàn thành tìm hiểu về cách cấu hình config.yml cho CircleCI

### ISSUE THREAD

**Issue by tuanhcmute** [tuanhcmute/Nhom1_CCPTPM#15]
Hoàn thành tìm hiểu về Circle CI và Docker

**Comment by mytranchi** [comment]
#### Tìm hiểu cách cấu hình Circle CI
##### File cấu hình config.yml
- Trong CircleCI, tệp config.yml là tệp cấu hình được sử dụng để định cấu hình các bước xây dựng, kiểm tra và triển khai ứng dụng. Đây là một tệp YAML, là một ngôn ngữ định dạng dữ liệu nhẹ, thường được sử dụng để đại diện cho cấu trúc dữ liệu.
- Tệp config.yml được đặt trong thư mục gốc của kho lưu trữ và cung cấp một tập hợp các chỉ thị và tùy chọn để chỉ định các bước xử lý, chẳng hạn như các công việc, workflow, môi trường và yêu cầu. Nó cũng cho phép cho ta định cấu hình các bộ dụng cụ và phiên bản của chúng, chạy các lệnh, chạy các bài kiểm tra và các tác vụ khác liên quan đến quá trình CI/CD.
- Các bước trong config.yml được định nghĩa dưới dạng các job và các job được sắp xếp thành các workflow để đảm bảo việc triển khai được thực hiện theo trình tự chính xác.
- File config.yml trong CircleCI cung cấp một cách tiếp cận linh hoạt để quản lý và tự động hóa quá trình CI/CD trong dự án phần mềm.

##### Các thành phần trong file config.yml

Trong config.xml thường chứa các thành phần như sau:

- Version: Phiên bản của CircleCI được sử dụng để xây dựng và triển khai.

- Orbs là các gói tái sử dụng được định nghĩa bởi CircleCI hoặc cộng đồng. Chúng cung cấp các công cụ và quy trình được đóng gói để giảm thiểu sự lặp lại trong các tệp cấu hình và giúp ta tập trung vào việc xây dựng ứng dụng của mình hơn.

- Jobs là các công việc được thực hiện trong quá trình xây dựng và kiểm tra. Mỗi công việc có thể chứa một hoặc nhiều bước. Các bước này có thể là các lệnh shell, các lệnh Docker hoặc các lệnh khác.

- Workflows là quy trình làm việc cho các công việc đã định nghĩa. Nó cho phép ta xác định một chuỗi các công việc và điều kiện để chạy chúng. Ví dụ :ta có thể chỉ muốn chạy một số công việc khi một số điều kiện nhất định được đáp ứng.

- Commands: là các lệnh thực thi được đặt tên và sử dụng lại trong tệp cấu hình. Điều này giúp giảm độ trùng lặp khi sử dụng các lệnh giống nhau trong nhiều công việc.

- Parameters: Tham số là giá trị được truyền vào các công việc hoặc lệnh trong quy trình. Tham số giúp linh hoạt trong việc sử dụng lại các công việc và lệnh.

- Environment: Môi trường định nghĩa các biến môi trường được sử dụng trong quy trình. Các biến môi trường có thể được sử dụng để chia sẻ thông tin giữa các công việc và đảm bảo rằng các giá trị được sử dụng cho môi trường xây dựng và triển khai đều giống nhau.

**Comment by tuanhcmute** [comment]
> ## Hoàn thành tìm hiểu về cách cấu hình config.yml cho CircleCI

- File config.yml được sử dụng để cấu hình và kiểm soát quá trình CI/CD (Continuous Integration/Continuous Deployment) trên CircleCI. Nó chứa các thông tin về các bước, công cụ, các lệnh cần thiết, hoặc các script để thực hiện các công việc như kiểm tra lỗi, đóng gói ứng dụng, deploy ứng dụng, và nhiều công việc khác.

- File config.yml thường được đặt tại thư mục gốc của project, cùng cấp với thư mục .git, và được đọc bởi CircleCI khi bạn commit và push mã nguồn lên repo của mình. Khi CircleCI phát hiện có bất kỳ thay đổi nào trên repo, nó sẽ tự động chạy các job đã được định nghĩa trong file config.yml.

- Qua đó, bạn có thể kiểm soát và tự động hoá các bước trong quá trình phát triển ứng dụng của mình, giúp tăng tính ổn định, đảm bảo chất lượng và tối ưu hóa quá trình phát triển ứng dụng của mình trên CircleCI.

### Một ví dụ về cấu hình circle đơn giản dùng config.yml
```
version: 2.1

orbs:
  python: circleci/python@1.2.0

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo
    steps:
      - checkout
      - python/install-packages:
          packages: requirements.txt
      - run:
          name: Run tests
          command: |
            python -m pytest tests/
    post:
      - store_artifacts:
          path: test-results.xml
          destination: test-results

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
```

- Trong ví dụ này, chúng ta đang sử dụng CircleCI Orb để quản lý các bản phát hành của Python, giúp cho việc cài đặt Python và các thư viện liên quan trở nên đơn giản hơn.

- Job `build` được định nghĩa để chạy các bước build và test cho ứng dụng Flask. Bước đầu tiên là checkout mã nguồn từ repo. Sau đó, chúng ta cài đặt các thư viện từ file `requirements.txt` thông qua Orb `python/install-packages`. Tiếp theo là chạy các test bằng lệnh `pytest`. Cuối cùng, chúng ta lưu kết quả test vào tệp `test-results.xml` bằng lệnh `store_artifacts`.

- Workflow `build-and-test` bao gồm một job duy nhất là job `build`.

- Với file `config.yml` này, khi bạn push code lên repository của mình, CircleCI sẽ tự động chạy job `build`, thực hiện các bước build và test ứng dụng của bạn, và lưu kết quả vào tệp `test-results.xml`.

### File cấu hình config.yml được sử dụng trong project
```
version: 2.1
orbs:
  python: circleci/python@1.5.0
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
      # Service container image
      # - image: cimg/postgres:14.0
      #   environment:
      #     POSTGRES_USER: root
      #     POSTGRES_DB: circle_test
      #     POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip

      - run:
          name: Database Setup
          command: |
            echo "circleci ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers.d/99-circleci
            sudo apt update && sudo apt install postgresql-client
            sudo service postgresql stop && sudo apt-get remove -y postgresql-9.4 && sudo apt-get update; sudo apt-get install -y postgresql postgresql-contrib
            sudo service postgresql restart
            echo "CREATE USER ubuntu WITH PASSWORD '1';" | sudo -u postgres psql

            sudo -u postgres createdb -O ubuntu apiDashboard

      - run:
          name: Run tests
          # This assumes pytest is installed via the install-package step above
          command: pytest

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test
```

- Trong file config trên khi được đẩy lên github. Thì sẽ install các packages của python. Sau đó install database trên môi trường docker chạy trên linux. Tiếp đó sẽ thực hiện tạo một user, database và cuối cùng sẽ chạy các testcase trên môi trường mà chúng ta đã setup
