### ISSUE TITLE
Hoàn thành tìm hiểu về cách kết nối CircleCI và Docker Image

### ISSUE THREAD

**Issue by tuanhcmute** [tuanhcmute/Nhom1_CCPTPM#17]
Hoàn thành tìm hiểu về Circle CI và Docker

**Comment by mytranchi** [comment]
#### Tìm hiểu cách kết nối Docker Image với Circle CI
##### Cách kết nối
Để kết nối Docker Image với Circle CI ta sẽ tiến hành cấu hình file config.yml
Với một số thông tin cấu hình sau:
```
version: 2
jobs:
  build:
    docker:
      - image: <docker-image-name>
    steps:
      - checkout
      - run: <command-to-run>
```
Trong đó:
docker-image-name là tên của Docker image mà ta muốn sử dụng.
command-to-run là lệnh mà ta muốn thực thi trong Docker image.
##### Kết nối Circle CI với Docker Image tích hợp trong Project
File cấu hình config.yml
```
version: 2.1
orbs:
  python: circleci/python@1.5.0
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
      # Service container image
      # - image: cimg/postgres:14.0
      #   environment:
      #     POSTGRES_USER: root
      #     POSTGRES_DB: circle_test
      #     POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip

      - run:
          name: Database Setup
          command: |
            echo "circleci ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers.d/99-circleci
            sudo apt update && sudo apt install postgresql-client
            sudo service postgresql stop && sudo apt-get remove -y postgresql-9.4 && sudo apt-get update; sudo apt-get install -y postgresql postgresql-contrib
            sudo service postgresql restart
            echo "CREATE USER ubuntu WITH PASSWORD '1';" | sudo -u postgres psql
            sudo -u postgres createdb -O ubuntu apiDashboard
      - run:
          name: Run tests
          # This assumes pytest is installed via the install-package step above
          command: pytest

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test
```
Trong đó: 
- version: 2.1: định dạng phiên bản cấu hình CircleCI, ở đây là phiên bản 2.1.

- orbs: phần này định nghĩa các ORB (Reusable Balls of YAML) để sử dụng trong tệp cấu hình. Ở đây, ORB circleci/python@1.5.0 được sử dụng để định nghĩa các bước cài đặt Python và các gói phụ thuộc.

- jobs: phần này định nghĩa các công việc (jobs) để thực hiện trong quá trình CI/CD. Ở đây, công việc build-and-test được định nghĩa để thực hiện các bước cài đặt và test ứng dụng Python.

    > docker: phần này định nghĩa Docker image mà CircleCI sẽ sử dụng để thực hiện các bước trong công việc build-and-test. Ở đây, Docker image cimg/python:3.10.2 được sử dụng để cài đặt và chạy ứng dụng Python.
    
    > steps: phần này định nghĩa các bước để thực hiện trong công việc build-and-test. Các bước bao gồm:
    checkout: sao chép mã nguồn của ứng dụng từ repository.
    python/install-packages: cài đặt các gói phụ thuộc của ứng dụng Python bằng pip.
    run: thực hiện các lệnh để thiết lập và chạy cơ sở dữ liệu PostgreSQL, bao gồm cài đặt PostgreSQL, tạo người dùng và cơ sở dữ liệu mới.
    run: thực hiện lệnh để chạy các bài kiểm tra của ứng dụng Python bằng pytest.

- workflows: phần này định nghĩa các luồng công việc (workflows) để thực hiện trong quá trình CI/CD. Ở đây, luồng công việc sample được định nghĩa để thực hiện công việc build-and-test.

**Comment by tuanhcmute** [comment]
> ## Hoàn thành tìm hiểu về cách kết nối CircleCI và Docker Image

- Ở những issue trước nhóm đã hoàn thành tìm hiểu về CircleCI và docker và hôm nay nhóm sẽ trình bày cách để sử dụng CircleCI trên môi trường docker trong dự án của nhóm

- Để chạy được CircleCI trên môi trường docker thì chúng ta cần có file config.yml

- Nội dung file config.yml của project
```
version: 2.1
orbs:
  python: circleci/python@1.5.0
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
      # Service container image
      # - image: cimg/postgres:14.0
      #   environment:
      #     POSTGRES_USER: root
      #     POSTGRES_DB: circle_test
      #     POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip

      - run:
          name: Database Setup
          command: |
            echo "circleci ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers.d/99-circleci
            sudo apt update && sudo apt install postgresql-client
            sudo service postgresql stop && sudo apt-get remove -y postgresql-9.4 && sudo apt-get update; sudo apt-get install -y postgresql postgresql-contrib
            sudo service postgresql restart
            echo "CREATE USER ubuntu WITH PASSWORD '1';" | sudo -u postgres psql
            sudo -u postgres createdb -O ubuntu apiDashboard
      - run:
          name: Run tests
          # This assumes pytest is installed via the install-package step above
          command: pytest

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test
```
- Với file config trên khi chúng ta đẩy code lên github thì github sẽ tự động gửi một yêu cầu chạy circleCI thì khi Circle chạy. Nó sẽ tự động tìm đến file config.yml này để tự động chạy build dự án trên môi trường docker và sau đó sẽ thực hiện các testcase
- Trong file config trên ta có một job là `buil-and-test`. Trong job này sẽ thực hiện các công việc sau: Thực hiện install các gói cần thiết để chạy được database management. Sau đó thực hiện start database đó, tiếp đến tạo một user trong database và cuối cùng tạo một database mẫu để có thể chạy được các test case.
